version: '3.6'

networks:
  proxy:
    external: true

services:
  bot:
    image: freqtradeorg/freqtrade:develop
    networks:
      - proxy
    volumes:
      - "./user_data:/freqtrade/user_data"
      - /home/webservice/bunni/repo/freqtrade/user_data/strategies:/freqtrade/user_data/strategies
      - /etc/timezone:/etc/timezone:ro
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --config /freqtrade/user_data/config.json
      --strategy ${STRATEGY}
      --db-url sqlite:///user_data/tradesv3.sqlite
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
      labels:
         - 'traefik.http.routers.freqtrade.tls=true'
         - 'traefik.http.routers.freqtrade.rule=Host(`${URL}`)'
         - 'traefik.http.services.freqtrade.loadbalancer.server.port=8080'

