
version: '3.7'

volumes:
  zoneminder-data:
    driver_opts:
      type: nfs
      o: addr=rockpiNAS,nolock,soft,rw
      device: :/export/DockerNFS/docker-volumes/zoneminder-data
  zoneminder-db:
    driver_opts:
      type: nfs
      o: addr=rockpiNAS,nolock,soft,rw
      device: :/export/DockerNFS/docker-volumes/zoneminder-db
    
networks:
  proxy:
    external: true
  zoneminder:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --log-bin=mysqld-bin --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - zoneminder
    volumes:
      - zoneminder-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=zm
      - MYSQL_USER=zm
      - TZ=America/Phoenix

  zoneminder:
    image: ghcr.io/zoneminder-containers/zoneminder-base:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
      labels:
        - 'traefik.http.routers.zoneminder.tls=true'
        - 'traefik.http.routers.zoneminder.rule=Host(`${SERVER_FQDN}`)'
        - 'traefik.http.services.zoneminder.loadbalancer.server.port=80'
    depends_on:
      - db
    networks:
      - zoneminder
      - proxy
    ports:
      - "8099:80"
    volumes:
      - zoneminder-data:/data
      - /mnt/glustervolume/zoneminder-config:/config
      - /mnt/glustervolume/zoneminder-log:/log
#      - type: tmpfs
#        target: /dev/shm
#        tmpfs:
#          size: 1000000000
    environment:
      - ZM_SERVER_HOST=zm
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=zm
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=America/Phoenix
      - MAX_LOG_SIZE_BYTES=1000000
      - MAX_LOG_NUMBER=20
#      - EMAIL_HOST=smtp.gmail.com
#      - EMAIL_PORT=587
#      - EMAIL_ADDRESS=zoneminder@omgthecloud.com
#      - EMAIL_PASSWORD=very_secure_password
