
version: '3.7'

volumes:
  zoneminder-data:
    driver_opts:
      type: nfs
      o: addr=rockpiNAS,nolock,soft,rw
      device: :/export/DockerNFS/docker-volumes/zoneminder-data
  
  zoneminder-db:
    external: true

#zoneminder 1 vols    
  zoneminder-config1:
    driver: glusterfs
    name: "gfs/zoneminder-config"
    
  zoneminder-log1:
    driver: glusterfs
    name: "gfs/zoneminder-log"
 
 #zoneminder 2 vols    
  zoneminder-config2:
    driver: glusterfs
    name: "gfs/zoneminder-config2"
    
  zoneminder-log2:
    driver: glusterfs
    name: "gfs/zoneminder-log2"
    
 #zoneminder 3 vols    
  zoneminder-config3:
    driver: glusterfs
    name: "gfs/zoneminder-config3"
    
  zoneminder-log3:
    driver: glusterfs
    name: "gfs/zoneminder-log3"
    
networks:
  proxy:
    external: true
  zoneminder:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --log-bin=mysqld-bin --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role != worker
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - zoneminder
    volumes:
      - zoneminder-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=zm
      - MYSQL_USER=zm
      - TZ=America/Phoenix

  zoneminder1:
    image: ghcr.io/zoneminder-containers/zoneminder-base:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
      labels:
        - 'traefik.http.routers.zoneminder.tls=true'
        - 'traefik.http.routers.zoneminder.rule=Host(`${SERVER_FQDN}`)'
        - 'traefik.http.services.zoneminder.loadbalancer.server.port=80'
    depends_on:
      - db
    networks:
      - zoneminder
      - proxy
    volumes:
      - zoneminder-data:/data
      - zoneminder-config1:/config
      - zoneminder-log1:/log
      - type: tmpfs
        target: /dev/shm
#        tmpfs:
#          size: 1000000000
    environment:
      - ZM_SERVER_HOST=zm1.arm.omgthecloud.com
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=zm
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=America/Phoenix
      - MAX_LOG_SIZE_BYTES=1000000
      - MAX_LOG_NUMBER=20
#      - EMAIL_HOST=smtp.gmail.com
#      - EMAIL_PORT=587
#      - EMAIL_ADDRESS=zoneminder@omgthecloud.com
#      - EMAIL_PASSWORD=very_secure_password

  zoneminder2:
    image: ghcr.io/zoneminder-containers/zoneminder-base:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
      labels:
        - 'traefik.http.routers.zoneminder2.tls=true'
        - 'traefik.http.routers.zoneminder2.rule=Host(`zm2.arm.omgthecloud.com`)'
        - 'traefik.http.services.zoneminder2.loadbalancer.server.port=80'
    depends_on:
      - db
    networks:
      - zoneminder
      - proxy
    volumes:
      - zoneminder-data:/data
      - zoneminder-config2:/config
      - zoneminder-log2:/log
      - type: tmpfs
        target: /dev/shm
#        tmpfs:
#          size: 1000000000
    environment:
      - ZM_SERVER_HOST=zm2.arm.omgthecloud.com
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=zm
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=America/Phoenix
      - MAX_LOG_SIZE_BYTES=1000000
      - MAX_LOG_NUMBER=20
#      - EMAIL_HOST=smtp.gmail.com
#      - EMAIL_PORT=587
#      - EMAIL_ADDRESS=zoneminder@omgthecloud.com
#      - EMAIL_PASSWORD=very_secure_password

  zoneminder3:
    image: ghcr.io/zoneminder-containers/zoneminder-base:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
      labels:
        - 'traefik.http.routers.zoneminder3.tls=true'
        - 'traefik.http.routers.zoneminder3.rule=Host(`zm3.arm.omgthecloud.com`)'
        - 'traefik.http.services.zoneminder3.loadbalancer.server.port=80'
    depends_on:
      - db
    networks:
      - zoneminder
      - proxy
    volumes:
      - zoneminder-data:/data
      - zoneminder-config3:/config
      - zoneminder-log3:/log
      - type: tmpfs
        target: /dev/shm
#        tmpfs:
#          size: 1000000000
    environment:
      - ZM_SERVER_HOST=zm3.arm.omgthecloud.com
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=zm
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=America/Phoenix
      - MAX_LOG_SIZE_BYTES=1000000
      - MAX_LOG_NUMBER=20
#      - EMAIL_HOST=smtp.gmail.com
#      - EMAIL_PORT=587
#      - EMAIL_ADDRESS=zoneminder@omgthecloud.com
#      - EMAIL_PASSWORD=very_secure_password
