
version: '3.7'

networks:
  proxy:
    external: true
  zoneminder:

volumes:
  zoneminder-data:
    driver: glusterfs
    name: "gfs/zoneminder-data"
 zoneminder-config:
    driver: glusterfs
    name: "gfs/zoneminder-config"
 zoneminder-logs:
    driver: glusterfs
    name: "gfs/zoneminder-logs"
 zoneminder-db:
    driver: glusterfs
    name: "gfs/zoneminder-db"

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - zoneminder
    volumes:
      - zoneminder-db/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=zm
      - MYSQL_USER=zm

  zoneminder:
    image: yaoa/zoneminder-base:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
      labels:
        - 'traefik.http.routers.zoneminder.tls=true'
        - 'traefik.http.routers.zoneminder.rule=Host(`${VIRTUAL_HOST}`)'
        - 'traefik.http.services.zoneminder.loadbalancer.server.port=80'
    depends_on:
      - db
    networks:
      - zoneminder
      - proxy
    volumes:
      - zoneminder-data:/data
      - zoneminder-config:/config
      - zoneminder-logs:/log
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 1000000000
    environment:
      - ZM_SERVER_HOST=zoneminder
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpassword
      - TZ=America/Phoenix
      - MAX_LOG_SIZE_BYTES=1000000
      - MAX_LOG_NUMBER=20
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_ADDRESS=zoneminder@omgthecloud.com
      - EMAIL_PASSWORD=very_secure_password
