version: "3.6"

networks:
  proxy:
    external: true

volumes:
  openproject-data:
    driver: glusterfs
    name: "gfs/openproject-data"
  openproject-assets:
    driver: glusterfs
    name: "gfs/openproject-assets"
    
services:
  openproject:
    image: "fazenda/openproject:latest"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
      labels:
        - 'traefik.http.routers.openproject.rule=Host(`${SERVER_FQDN}`)'
        - 'traefik.http.routers.openproject.tls=true'
        - 'traefik.http.services.openproject.loadbalancer.server.port=80'
    volumes:
      - openproject-data:/var/openproject/pgdata
      - openproject-assets:/var/openproject/assets
    networks:
      - proxy

    environment:
      - SERVER_HOSTNAME=${SERVER_FQDN}
      - SHOW_WARNING_BARS=false
      - SECRET_KEY_BASE=${SECRET_KEY}
      - EMAIL_DELIVERY_METHOD=smtp
      - SMTP_ADDRESS=email-smtp.us-east-1.amazonaws.com
      - SMTP_PORT=587
      - SMTP_DOMAIN=${SMTP_DOMAIN}
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_USER_NAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
